version: "3.7"
services:
  web:
    build: .
    environment:
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_HOST: $DATABASE_HOST
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' && rails db:migrate && rails db:seed"
    stdin_open: true  # コンテナの標準入力を開く
    tty: true         # コンテナの標準入力を維持する
  db:
    image: postgres:latest
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - "5432:5432"
    # ホストのカレントディレクトリ(.)とイメージ内の/myappディレクトリを同期させている
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
volumes:
  postgres-data:
    driver: local
