default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "root" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  port: 3306
  host: "127.0.0.1"

test:
  <<: *default
  database: chem-chem_ci_test
