name: test

on:
  push:

jobs:
  test-runner:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          DATABASE_USERNAME: test_user
          DATABASE_PASSWORD: test_password
          POSTGRES_DB: train-nari_test
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Show Docker containers
        run: docker ps -a

      - name: Show databases for test_user
        run: PGPASSWORD=test_password psql -h localhost -p 5432 -U test_user -d train-nari_test -c "SELECT datname FROM pg_database"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Bundler and gem install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Database create and migrate
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Run rubocop
        run: bundle exec rubocop

      - name: Run Rails best practices
        run: bundle exec rails_best_practices .
